### PR TITLE
Databasefix

### PR DESCRIPTION
**Pull request by hanzheg**

### CODE REVIEW

**Comment by yangjus** [comment]
Possibly change the title of dataset from Variables selection to be without underscores, similar to how you did it for the title of dataset from Datasets selection.

**Comment by yangjus** [comment]
isFetched is not used. file variable for locateFile is not used.

**Comment by yangjus** [comment]
image
Occurs when initial load, no query is made. Handle this edge case.

**Comment by hanzheg** [comment]
> isFetched is not used. file variable for locateFile is not used.

delete, fetched variable, but keep the await queryDatabase otherwise it may cause error

**Comment by hanzheg** [comment]
> Possibly change the title of dataset from Variables selection to be without underscores, similar to how you did it for the title of dataset from Datasets selection.

Did data cleaning when inserting to new DB, will be solved once I move to new DB

**Comment by hanzheg** [comment]
> isFetched is not used. file variable for locateFile is not used.

investigating

**Comment by hanzheg** [comment]
> image Occurs when initial load, no query is made. Handle this edge case.

Solved

**Pull request merged**
